### PR TITLE
Add support for Karafka

### PR DESCRIPTION
**Pull request by mensfeld**
This PR adds the magical dashboard setup for Karafka framework.

cc @thijsc

### CODE REVIEW

**Review by thijsc — APPROVED** [review]

**Comment by unflxw** [comment]
Is there anything that needs to be done before merging this @mensfeld @thijsc?

**Comment by mensfeld** [comment]
@unflxw it LGTM on my side. Nothing more needed. Please ping me once available in appsignal to I can test it end-to-end

**Comment by unflxw** [comment]
@mensfeld Will do! Note that you can also test it by creating a new dashboard, selecting "Import dashboard", and pasting **the value for the `dashboard` top-level property (not the whole object!)**.

**Comment by mensfeld** [comment]
@unflxw I know. This I tested :) I just wanted to see the automatic detection in action

**Comment by unflxw** [comment]
Ah, perfect! I'll ping you when it's in production, then.

**Pull request merged**
